config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :profiles
  resources :sessions

  root 'welcome#index'
  get 'admin_user' => 'welcome#admin_user', as: :admin_user
  get 'admin' => 'welcome#admin', as: :admin_index
  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :categories
    resources :promotions
    resources :beacons
    get '/users/:id' => 'users#update', as: :user_edited
  end

  namespace "owner" do
    resources :commerces do
      resources :stores do
        resources :promotions
      end
    end
  end
  
  namespace "api" do
    resources :commerces
    resources :stores
    resources :promotions
    resources :beacons
    resources :categories    
  end

  get 'my_profile' => 'users#my_profile', as: :my_profile

end

app/views/admin/_menu.html.erb
            </li>
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-users"></i> 
                  <span>Usuarios</span> 
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li>
                  <a href="<%=admin_users_path%>"><i class="glyphicon glyphicon-zoom-in"></i> Ver Usuarios</a>
                  </li>
                  <li>
                  <a href="<%=new_admin_user_path%>"><i class="fa fa-user-plus"></i> Agregar Usuario</a>
                  </li>
                </ul>
              </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-building-o"></i> 
                <span>Comercios</span> 
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li>
                <a href="<%=admin_commerces_path%>"><i class="glyphicon glyphicon-zoom-in"></i> Ver Comercios</a>
                </li>
                <li>
                <a href="<%=new_admin_commerce_path%>"><i class="fa  fa-plus-square-o"></i> Agregar Comercio</a>
                </li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-industry"></i> 
                <span>Categorias</span> 
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li>
                <a href="<%=admin_categories_path%>"><i class="glyphicon glyphicon-zoom-in"></i> Ver Categorías</a>
                </li>
                <li>
                <a href="<%=new_admin_category_path%>"><i class="fa  fa-plus-square-o"></i> Agregar Categoría</a>
                </li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-cart-arrow-down"></i> 
                <span>Tiendas</span> 
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li>
                <a href="<%=admin_stores_path%>"><i class="fa fa-cart-plus"></i> Ver Tiendas</a>
                </li>
                <li>
                <a href="<%=new_admin_store_path%>"><i class="fa  fa-plus-square-o"></i> Agregar Tienda</a>
                </li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-bold"></i> 
                <span>Beacons</span> 
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li>
                <a href="<%=admin_beacons_path%>"><i class="glyphicon glyphicon-zoom-in"></i> Ver Beacons</a>
                </li>
                <li>
                <a href="<%=new_admin_beacon_path%>"><i class="fa  fa-plus-square-o"></i> Agregar Beacon</a>
                </li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="glyphicon fa fa-star-o"></i> 
                <span>Promociones</span> 
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li>
                <a href="<%=admin_promotions_path%>"><i class="fa fa-star-half-empty"></i> Ver Promociones</a>
                </li>
                <li>
                <a href="<%=new_admin_promotion_path%>"><i class="fa  fa-plus-square-o"></i> Agregar Promoción</a>
                </li>
              </ul>
            </li>