config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :profiles
  resources :sessions

  root 'welcome#index'
  get 'admin_user' => 'welcome#admin_user', as: :admin_user
  get 'admin' => 'welcome#admin', as: :admin_index
  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :categories
    resources :promotions
    resources :beacons
    get '/users/:id' => 'users#update', as: :user_edited
  end

  namespace "owner" do
    resources :commerces do
      resources :stores do
        resources :promotions
      end
    end
  end
  
  namespace "api" do
    resources :commerces
    resources :stores
    resources :promotions
    resources :beacons
    resources :categories    
  end

  get 'my_profile' => 'users#my_profile', as: :my_profile

end

app/models/promotion.rb
class ActivatesValidator < ActiveModel::Validator
  def validate(record)
  	puts "***"+record.send(options[:fields][0]).to_s
  	if record.send(options[:fields][0])==true
    	puts "OK active"
    	array = Store.find(record.send(options[:fields][1])).promotions.where("active =? AND id!=?","true",record.send(options[:fields][2]))
    	if array.size>0
	      record.errors[:message] = "Esta tienda ya posee una promoción activa"
    		
    	end
    end
  end
end
class Promotion < ActiveRecord::Base

	belongs_to :store
	after_initialize :init
 	extend FriendlyId
  	friendly_id :title, use: :slugged
	validates :title, :presence => {:message => "El campo Título no puede estar vacío"}
	validates :until, :presence => {:message => "El campo Caducidad no puede estar vacío"}
	validates :price, :presence => {:message => "El campo Precio no puede estar vacío"}
	validates :store_id, :presence => {:message => "Debe indicar la Tienda"}
	validates_with ActivatesValidator, fields: [:active,:store_id,:id]

	def init
		self.picture  ||= "/photo_store/default_promotion.png"
		self.active =  false if self.active.nil?
	end	
	
	def state
		return self.active ? "Activa" : "Inactiva"
	end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < ApplicationController
  before_action :require_admin_login
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotions = Promotion.all
    render "index"
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new

  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to admin_promotion_path(@promotion), notice: 'Promoción creada exitosamente.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      @promotion.slug=nil
      if @promotion.update(promotion_params)
        format.html { redirect_to admin_promotion_path(@promotion), notice: 'Promoción actualizada exitosamente.' }
        msg = { :status => "ok", :message => "Success!", :promotion => @promotion }
        format.json  { render :json => msg } # don't do msg.to_json
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:title, :description, :picture, :price,:store_id,:until,:active)
    end
end

app/controllers/api/promotions_controller.rb
class Api::PromotionsController < ApplicationController
  skip_before_action :require_login
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to admin_promotions_path, notice: 'Categoria creada exitosamente.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      @promotion.slug=nil
      if @promotion.update(promotion_params)
        format.html { redirect_to admin_promotions_path, notice: 'Categoria actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:name, :description)
    end
end

app/controllers/owner/promotions_controller.rb
class Owner::PromotionsController < ApplicationController
  before_action :require_owner_login
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]
  before_action :set_store

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = @store.promotions
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotions = @store.promotions
    render "index"
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new

  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)
    @promotion.store=@store
    respond_to do |format|
      if @promotion.save
        format.html { redirect_to owner_commerce_store_promotion_path(@store.commerce,@store,@promotion), notice: 'Promoción creada exitosamente.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      @promotion.slug=nil
      if @promotion.update(promotion_params)
        format.html { redirect_to owner_commerce_store_promotion_path(@store.commerce,@store,@promotion), notice: 'Promoción actualizada exitosamente.' }
        msg = { :status => "ok", :message => "Success!", :promotion => @promotion }
        format.json  { render :json => msg } # don't do msg.to_json
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:title, :description, :picture, :price,:until,:active)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/admin/promotions/_form.html.erb
<%= form_for(@promotion,url: (@promotion.new_record? ? admin_promotions_url : admin_promotion_url),:html => {:class => "form-with-img form-no-submit"}) do |f| %>
  <script type="text/javascript">
   var errorsArray=[] ;
  <% @promotion.errors.each do |atributo, mensaje| %>
      errorsArray.push({atributo:"<%="#{atributo}"%>",mensaje:"<%="#{mensaje}"%>"});
  <% end %>
  $( document ).ready(function() {
    validarErrores(errorsArray);
  });
</script>

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Datos de la Promoción</h3>
    </div><!-- /.box-header -->

    <div class="box-body">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="field">
            <%=f.label :photo, "Imagen de la promoción"%><br>
            <%= image_tag @promotion.picture, id: "containerImage", class: "img-upload"%><br>
            <button type="button" style="margin-top:5px;" class="btn btn-default"  onclick="$('#file').click();">
              <span class="glyphicon glyphicon-camera" aria-hidden="true" style="margin-right:5px;" ></span>
              Cargar Imagen &nbsp;
            </button>
          </div>
          <script>
            var loadFile = function(event) {
              var reader = new FileReader();
              reader.onload = function(){
                var output = document.getElementById('containerImage');
                output.src = reader.result;
              };
              reader.readAsDataURL(event.target.files[0]);
            };

          </script>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :title, "Título" %>*<br>
              <%= f.text_field :title,class:"form-control" %>
            </div>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :description, "Descripción" %><br>
              <%= f.text_area :description ,class:"form-control" %>
            </div>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :until, "Caducidad" %>*<br>
                <div class="input-group date">
                  <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                  </div>
                   <%= f.text_field :until ,class:"form-control pull-right",id:"datepicker" %>
                </div>
            </div>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :price, "Precio" %>*<br>
              <div class="input-group date">
                <div class="input-group-addon">
                  <b>$</b>
                </div>
                <%= f.text_field :price ,class:"form-control pull-right money" %>
              </div>
            </div>
        </div>
      </div>
       <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="form-group">
            <%= f.label :store_id, "Tienda asociada" %>*<br>
            <%= f.select :store_id, options_for_select(Store.all.pluck(:name,:id),( @promotion.store ? @promotion.store_id : "" )),{},{class:"form-control select2"}%>
          </div>
        </div>
      </div>         

    </div><!-- /.box-body -->
  </div><!-- /.box -->
  
    <div class="box-footer">
      <button type="button" style="margin-top:5px;" class="visible-xs btn btn-block btn-primary btn-lg" aria-label="Left Align" onclick="submitForm('promotion');"><%= (@promotion.new_record? ? "Crear Promoción" : "Actualizar Promoción")%></button>
    <button type="button" style="margin-top:5px;" class="hidden-xs btn btn-primary" aria-label="Left Align" onclick="submitForm('promotion');"><%= (@promotion.new_record? ? "Crear Promoción" : "Actualizar Promoción")%></button>
    </div>
<% end %>

<div class="hidden">
  <form id = "file-img" method="POST" action="http://uploads.im/api?upload" enctype="multipart/form-data">
    <input type="file" id="file" name="file" onchange= "loadFile(event)" />
    <input type="submit" value="SEND FILE">
  </form>
</div>
<!-- bootstrap datepicker -->
<script src="/plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="/plugins/datepicker/locales/bootstrap-datepicker.es.js"></script>
<script>
      $(function () {
      


        //Initialize Select2 Elements
        $(".select2").select2();
        //$("#datepicker").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
            $('#datepicker').datepicker({
              startDate: '+1d',
              autoclose: true,
              language:'es',
              format: 'dd/mm/yyyy'
            });


      });
</script>

app/views/admin/promotions/_promotions_table.html.erb
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Promociones</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="promotions_table" class="display table table-bordered table-striped" cellspacing="0" wilabelh="100%">
                    <thead>
                      <tr>
                        <th>Código</th>
                        <th>Titulo</th>
                        <th>Precio</th>
                        <th>Vence</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @promotions.each_with_index do |promotion,index| %>
                      <tr class="detail-inside link <%=promotion.active ? 'tr-active' : 'tr-inactive' %>" data-toggle="modal" data-target=<%="#modal-promotion-"+promotion.id.to_s%> data-url="<%=admin_promotion_path(promotion)%>">
                        <td><%= promotion.id %></td>
                        <td ><%= promotion.title %></td>
                        <td class="money"><%= promotion.price %></td>
                        <td ><%= promotion.until %></td>
                      </tr>
                        <div class="example-modal">
                          <div class="modal fade detail-promotion" id=<%="modal-promotion-"+promotion.id.to_s%>>
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hispanen="true">&times;</span></button>
                                  <h4 class="modal-title">Información</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="row">
                                    <div class="col-xs-12">
                                      <div class="box box-solid">
                                        <div class="box-header with-border">
                                          <i class="fa fa-text-wilabelh"></i>
                                          <h3 class="box-title">Datos de la promoción</h3>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                          <div class="row">
                                            <div class="col-xs-12 col-sm-6">
                                              <%= image_tag promotion.picture,class: "img-detail"%>
                                            </div>
                                            <div class="col-xs-12 col-sm-6">
                                              <dl class="dl-horizontal">
                                                <label>Codigo:</label>
                                                <span><%=promotion.id%></span><br>
                                                <label>Tienda Asociada:</label>
                                                <span><%=promotion.store.name%> (<%=promotion.store.commerce.name%>)</span><br>
                                                <label>Título:</label>
                                                <span><%=promotion.title%></span><br>
                                                <label>Precio:</label>
                                                <span class="money"><%=promotion.price%></span><br>
                                                <label>Vence:</label>
                                                <span><%=promotion.until%></span><br>
                                                <label>Estado:</label>
                                                <span><%=promotion.state%></span><br>
                                                <label>Descripción:</label><br>
                                                <span><%=promotion.description%></span><br>
                                                                                  
                                              </dl>

                                            </div>

                                          </div>

                                        <button data-url=<%=admin_promotion_path(promotion)%> data-model="promotion" data-model-description="Promoción"  type="button" class="btn <%= promotion.active ? "btn-warning" : "btn-success"%> change_status"><%= promotion.active ? "Desactivar" : "Activar"%></button>
                                       </div><!-- /.box-body -->
                                      </div><!-- /.box -->
                                      <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="window.location.href='<%=admin_store_path(promotion.store)%>'"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Ver tienda asociada &nbsp;</button>
                                    </div><!-- ./col -->
                                  </div><!-- /.row -->
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                                  
                                  <button data-url=<%=admin_promotions_path%> data-id=<%=promotion.id%> type="button" class="btn btn-danger delete-record">
                                     <span class="glyphicon glyphicon-trash" aria-hispanen="true"></span> Eliminar</button>
                                  <button type="button" class="btn btn-primary" aria-label="Left Align" 
                                    onclick="window.location.href=
                                    '<%=edit_admin_promotion_path(promotion) %>'">
                                    <span class="glyphicon glyphicon-pencil" aria-hispanen="true"></span> Editar &nbsp;
                                  </button>
                                </div>
                              </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                          </div><!-- /.modal -->
                        </div><!-- /.example-modal -->
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Código</th>
                        <th>Titulo</th>
                        <th>Precio</th>
                        <th>Vence</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

      <script>
      $(function () {
        $("#promotions_table").DataTable({
          "language": {
            "url": "/plugins/datatables/dataTables.spanish.lang"
          },
          "columnDefs": [ {
          "targets": 'no-sort',
          "orderable": false,
          "searchable": false
          } ],
          stateSave: true
        });
        var promotion_id = "<%=@promotion!=nil ? @promotion.id.to_s : nil%>"
        if (promotion_id.trim().length>0) {
          $("#modal-promotion-"+promotion_id).modal("show")
        }
        var current_state={target:null};
        window.onpopstate = function(e){
           if(e.state){
                if(e.state.target && current_state.target!=e.state.target){
                  current_state=e.state;
                  $.each($(".detail-promotion"), function( index, element ) {
                    $(element).modal("hide");
                  });
                  $.each($(".modal-backdrop"), function( index, element ) {
                    $(element).remove()
                  });
                  setTimeout(function(){$(e.state.target).modal("show");},0)
                }                
            }
        };
      });
      </script>

app/views/admin/promotions/index.html.erb
       <!-- Main content -->
        <section class="content">
          <%= render 'promotions_table' %>
        </section><!-- /.content -->

<br>

    <%= link_to 'Nueva Promoción', new_admin_promotion_path ,class:"visible-xs btn btn-block btn-primary btn-lg"%>
    <%= link_to 'Nueva Promoción', new_admin_promotion_path ,class:"hidden-xs btn btn-primary "%>