config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :profiles
  resources :sessions

  root 'welcome#index'
  get 'admin_user' => 'welcome#admin_user', as: :admin_user
  get 'admin' => 'welcome#admin', as: :admin_index
  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :categories
    resources :promotions
    resources :beacons
    get '/users/:id' => 'users#update', as: :user_edited
  end

  namespace "owner" do
    resources :commerces do
      resources :stores do
        resources :promotions
      end
    end
  end
  
  namespace "api" do
    resources :commerces
    resources :stores
    resources :promotions
    resources :beacons
    resources :categories    
  end

  get 'my_profile' => 'users#my_profile', as: :my_profile

end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "Debe introducir un Email válido")
    end
  end
end

class User < ActiveRecord::Base
	authenticates_with_sorcery!
	attr_accessor  :password, :password_confirmation
	has_many :commerces,dependent: :destroy
	belongs_to :role
	has_one :profile, dependent: :destroy
	accepts_nested_attributes_for :profile, allow_destroy: true
	extend FriendlyId
	friendly_id :email, use: :slugged

	#Validaciones
	validates :email, :presence => {:message => "El campo email no puede estar vacío"}
	validates :email, :uniqueness => {:message => "Ya existe un usuario con este correo"}
	validates :email, email:  true
	validates :password, length: {:if => :password_required?, minimum: 8 , message:"El campo contraseña debe contener al menos 8 dígitos"}
	validates :password, :presence =>  { :if => :password_required?, :message => "El campo contraseña no puede estar vacío"}
	validates :password, :confirmation =>  { :if => :password_required?, :message => "Las contraseñas no coinciden"}
	validates :password_confirmation, :presence =>  { :if => :password_required?, :message => "El campo confirmar contraseña no puede estar vacío"}
  def password_required?
    new_record?
  end
  def admin?
    self.role.name=="Admin"
  end

  def owner?
    self.role.name=="Owner"
  end

  def seller?
    self.role.name=="Seller"
  end
	def role_name
	    puts "role******"
	    if !self.role_id?
	      return "S/R"
	    end
	    if self.admin?
	      return "Administrador"
	    end
	    if self.owner? 
	      if self.commerces.count>0
	        count = self.commerces.count
	        return "Propietari"+(self.profile.sex==true ? "o": "a")+" de "+count.to_s+" Comercio"+(count>1 ? "s" : "")
	      else
	        return "Owner"
	      end
	    end
	    if self.seller?
	      return "Vendedor"+(self.profile.sex ? "" : "a")+" en la tienda "+self.sellers.first.store.nombre 
		end
		end  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin_login
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 # before_action :validate_password, only:[:create]
  # GET /users_url
  # GET /users.json
  def index
      @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'Usuario creado exitosamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      @user.slug=nil
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'Usuario actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def my_profile
    @user = current_user
    render 'edit'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,:role_id,profile_attributes: [:id,:name, :last_name, :sex, :phone, :_destroy])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:my_profile, :update]


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      @user.slug=nil
      if @user.update(user_params)
        ruta = @user==current_user ? root_path : users_path
        format.html { redirect_to ruta, notice: 'Perfil actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 def my_profile
    render 'edit'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,:role_id,profile_attributes: [:id,:name, :last_name, :sex, :phone, :_destroy])
  end

end

app/views/admin/users/_form.html.erb
<%= form_for(setup_user(@user),url: (@user.new_record? ? admin_users_url : admin_user_edited_url(@user) )) do |f| %>


  <script type="text/javascript">
   var errorsArray=[] ;
  <% @user.errors.each do |atributo, mensaje| %>
      errorsArray.push({atributo:"<%="#{atributo}"%>",mensaje:"<%="#{mensaje}"%>"});
  <% end %>
  $( document ).ready(function() {
    validarErrores(errorsArray);
  });
</script>
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Datos Personales</h3>
        </div><!-- /.box-header -->

        <div class="box-body">
          
          <%= f.fields_for :profile do |field| %>
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                  <%= f.label :email, "Email"%>*<br>
                  <%= f.text_field :email,class:"form-control"  %>
                 </div>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                  <%= field.label :sex, "Sexo" %>*<br>
                  <%= field.radio_button :sex,'true', :checked => true %>
                  Masculino              
                  <%= field.radio_button :sex,'false', :checked => false %>
                  Femenino
                </div>
              </div>        
            </div>
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                  <%= field.label :name, "Nombres" %>*<br>
                  <%= field.text_field :name,class:"form-control" %>
                </div>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                  <div class="form-group">
                    <%= field.label :last_name, "Apellidos" %><br>
                    <%= field.text_field :last_name,class:"form-control"  %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                  <%= field.label :phone,"Celular" %><br>
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <%= field.text_field :phone,class:"form-control", "data-inputmask" => '"mask": "+99 (999) 999-9999"'  %>
                  </div><!-- /.input group -->
                </div>
              </div>
            </div>
          <% end %>
        </div><!-- /.box-body -->
      </div><!-- /.box -->      
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Contraseña de ingreso</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <%= f.label :password, "Contraseña"%>*<br>
                <%= f.password_field :password,class:"form-control"  %>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                 <%= f.label :password_confirmation, "Confirmar contraseña" %>*<br />
                 <%= f.password_field :password_confirmation,class:"form-control" %>
               </div>
            </div>
          </div>
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <div class="form-group">
                  <%= f.label :role_id, "Rol del usuario" %>*<br>
                <%= f.select :role_id, options_for_select(Role.all.pluck(:name,:id),( @user.role ? @user.role_id : "" )),{},{class:"form-control select2"}%>
                </div>
              </div>
            </div>
        </div>
      </div><!-- /.box -->
      <div class="box-footer">
        <%= f.submit "Guardar", class: "visible-xs btn btn-block btn-primary btn-lg" %>
        <%= f.submit "Guardar", class: "hidden-xs btn btn-primary" %>
      </div>

    </div>
  </div>

<% end %>

 <script>
      $(function () {
        $("#user_profile_attributes_phone").inputmask();
          $('input[type="radio"]').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass: 'iradio_minimal-blue'
        });
          $('input[type="radio"]').first().parent().addClass("checked")
          $(".select2").select2();
          
          alertmsj = "<%=alert%>"
          validarMensajes();


      });
</script>

app/views/admin/users/edit.html.erb
<h1>Editar Usuario</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
       <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Usuarios</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="users_table" class="display table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        <th>Correo</th>
                        <th>Nombre</th>
                        <th>Celular</th>
                        <th class="hidden-xs">Rol</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @users.each_with_index do |user,index| %>
                        <tr class="link" data-toggle="modal" data-target=<%="#modal-user-"+index.to_s%>>
                          <td><%= user.email %></td>
                          <td><%= user.profile.short_name %></td>
                          <td><%= user.profile.phone %></td>
                          <td class="hidden-xs"><%= user.role_name%></td>
                        </tr>
                        <div class="example-modal">
                          <div class="modal fade" id=<%="modal-user-"+index.to_s%>>
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                  <h4 class="modal-title">Información</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="row">
                                    <div class="col-xs-12">
                                      <div class="box box-solid">
                                        <div class="box-header with-border">
                                          <i class="fa fa-text-width"></i>
                                          <h3 class="box-title">Datos de <%=user.profile.short_name%></h3>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                          <dl>
                                            <dt>Correo:</dt>
                                            <dd><%=user.email%></dd>
                                            <dt>Nombre completo:</dt>
                                            <dd><%=user.profile.complete_name%></dd>
                                            <dt>Sexo:</dt>
                                            <dd><%=user.profile.sex_name%></dd>
                                            <dt>Teléfono celular:</dt>
                                            <dd><%=user.profile.phone%></dd> 
                                            <dt>Rol:</dt>
                                            <dd><%=user.role_name%></dd> 
                                          </dl>
                                       </div><!-- /.box-body -->
                                      </div><!-- /.box -->
                                    </div><!-- ./col -->
                                  </div><!-- /.row -->
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                                  
                                  <button data-url=<%=admin_users_path%> data-id=<%=user.id%> type="button" class="btn btn-danger delete-record">Eliminar</button>
                                  <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="window.location.href='<%=edit_admin_user_path(user)%>'">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar &nbsp;
                                  </button>
                                </div>
                              </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                          </div><!-- /.modal -->
                        </div><!-- /.example-modal -->
                          
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Cédula</th>
                        <th>Nombre</th>
                        <th>Celular</th>
                        <th class="hidden-xs">Rol</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->




 <script>
      $(function () {
        $("#users_table").DataTable({
          "language": {
            "url": "/plugins/datatables/dataTables.spanish.lang"
          },
          "columnDefs": [ {
          "targets": 'no-sort',
          "orderable": false,
          "searchable": false
          } ],
          stateSave: true
        });
      });
</script>

<br>



        <%= link_to 'Nuevo  usuario', new_admin_user_path ,class:"visible-xs btn btn-block btn-primary btn-lg"%>
        <%= link_to 'Nuevo  usuario', new_admin_user_path ,class:"hidden-xs btn btn-primary "%>

app/views/admin/users/new.html.erb
	<%= render 'form' %>

app/views/admin/users/show.html.erb
<p>
  <strong>Cedula:</strong>
  <%= @user.cedula %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Regresar', users_path %>